apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: go-app 
  description: Secure Supply Chain Example for Go is an open source programming language that makes it easy to build simple, reliable, and efficient software.   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags: ["go", "ssc", "sbom", "acs"] 
spec:
  type: service
  owner: group:default/guests 
  lifecycle: experimental
